<?php $helper = Mage::helper('onestepcheckout') ?>
		<?php $fieldValue = $helper->getFieldValue() ?>
		<?php $checkCountry = 0 ?>
		<?php $checkRegion = 0 ?>
		<?php for($i=0;$i<20;$i++): ?>
		
			<?php if($i==5){?>
			<li class="wide">
				<label class="required" for="billing:paypalcomment"><?php echo $this->__('Comment') ?></label><br>
				<div class="input-box">
					<textarea rows="5" cols="10" style="width:240px;" class="input-text" title="<?php echo $this->__('Comment') ?>" id="billing:paypalcomment" name="billing[paypalcomment]"></textarea>
				</div>
			</li>
			<?php } ?>
			<?php if($helper->getFieldEnable($i)=='country') $checkCountry = 1 ?>
			<?php if($helper->getFieldEnable($i)=='region') $checkRegion = 1 ?>
			<?php if(Mage::getSingleton('customer/session')->isLoggedIn() && $helper->getFieldEnable($i)=='email') continue; ?>
			<?php if(!$helper->getFieldEnable($i)||$helper->getFieldEnable($i)=='0') continue; ?>
			<?php if(($i%2==0) || (($i%2!=0)&&(!$helper->getFieldEnable($i-1)||$helper->getFieldEnable($i-1)=='0'||(Mage::getSingleton('customer/session')->isLoggedIn() && $helper->getFieldEnable($i-1)=='email')))): ?>
				<li>
			<?php endif ?>
				<?php if((($i%2==0) && ($helper->getFieldEnable($i)&&$helper->getFieldEnable($i)!='0') && (!$helper->getFieldEnable($i+1)||$helper->getFieldEnable($i+1)=='0'||(Mage::getSingleton('customer/session')->isLoggedIn() && $helper->getFieldEnable($i+1)=='email')))
						|| (($i%2!=0) && ($helper->getFieldEnable($i)&&$helper->getFieldEnable($i)!='0') && (!$helper->getFieldEnable($i-1) || $helper->getFieldEnable($i-1)=='0'||(Mage::getSingleton('customer/session')->isLoggedIn() && $helper->getFieldEnable($i-1)=='email')))): ?>
					<div class="one-field">
				<?php else: ?>
					<div class="two-fields">
				<?php endif ?>
				<?php if(!$helper->getFieldEnable($i)||$helper->getFieldEnable($i)=='0') continue; ?>
						<?php if($helper->getFieldEnable($i)=='country'): ?>
							<label for="billing:country_id"><?php echo $this->__('Country') ?>
								<?php if($helper->getFieldRequire($helper->getFieldEnable($i))): ?>
									<span class="required">*</span>
								<?php endif ?>
							</label><br />
							<?php echo $this->getCountryHtmlSelect('billing') ?>
							<?php if(!$helper->getFieldRequire($helper->getFieldEnable($i))): ?>	
								<script type="text/javascript">
									if($('billing:country_id'))
										$('billing:country_id').removeClassName('validate-select');
								</script>
							<?php endif ?>
						<?php elseif($helper->getFieldEnable($i)=='suffix'): ?>
							<?php $customerNameBlock = Mage::getBlockSingleton('customer/widget_name') ?>
							<label for="billing:prefix"><?php echo $this->__('Suffix Name') ?>
								<?php if($helper->getFieldRequire($helper->getFieldEnable($i))): ?>
									<span class="required">*</span>
								<?php endif ?>
							</label><br />
							<?php if ($customerNameBlock->getSuffixOptions()===false): ?>
								<input type="text" id="<?php echo $customerNameBlock->getFieldId('suffix')?>" name="billing[<?php echo $customerNameBlock->getFieldName('suffix')?>]" value="" title="<?php echo $this->__('Suffix') ?>" class="input-text <?php if($helper->getFieldRequire($helper->getFieldEnable($i))) echo "required-entry"; ?>" <?php echo $customerNameBlock->getFieldParams() ?> />
							<?php else: ?>
								<select id="<?php echo $customerNameBlock->getFieldId('suffix')?>" name="billing[<?php echo $customerNameBlock->getFieldName('suffix')?>]" title="<?php echo $this->__('Suffix') ?>" class="<?php if($helper->getFieldRequire($helper->getFieldEnable($i))) echo "required-entry"; ?>" <?php echo $customerNameBlock->getFieldParams() ?>>
									<?php foreach ($customerNameBlock->getSuffixOptions() as $_option): ?>
										<option value="<?php echo $_option?>"><?php echo $this->__($_option)?></option>
									<?php endforeach ?>
								</select>
							<?php endif; ?>
							<?php elseif($helper->getFieldEnable($i)=='gender'): ?>
							<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
							<label for="<?php echo $_gender->getFieldId('gender')?>"><?php echo $this->__('Gender') ?>
								<?php if($helper->getFieldRequire($helper->getFieldEnable($i))): ?>
									<span class="required">*</span>
								<?php endif ?>
							</label><br />
							<select id="<?php echo $_gender->getFieldId('gender')?>" name="billing[<?php echo $_gender->getFieldName('gender')?>]" title="<?php echo $this->__('Gender') ?>" class="<?php if($helper->getFieldRequire($helper->getFieldEnable($i))) echo "validate-select"; ?>" <?php echo $_gender->getFieldParams() ?>>
								<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
								<?php $value = $_gender->getGender();?>
								<?php foreach ($options as $option):?>
									<option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
								<?php endforeach;?>
							</select>
						<?php elseif($helper->getFieldEnable($i)!='street' && $helper->getFieldEnable($i)!='city' && $helper->getFieldEnable($i)!='region' && $helper->getFieldEnable($i)!='postcode'): ?>
							<label for="billing:<?php echo $helper->getFieldEnable($i); ?>"><?php echo $this->__($fieldValue[$helper->getFieldEnable($i)]) ?>
								<?php if($helper->getFieldRequire($helper->getFieldEnable($i)) || $helper->getFieldEnable($i)=='firstname'||$helper->getFieldEnable($i)=='lastname'|| $helper->getFieldEnable($i)=='email'): ?>
									<span class="required">*</span>
								<?php endif ?>
							</label><br/>
							<input type="text" <?php if($helper->getFieldEnable($i)=='email'){ ?> onblur="validate_email()" <?php } ?> id="billing:<?php echo $helper->getFieldEnable($i); ?>" name="billing[<?php echo $helper->getFieldEnable($i); ?>]" value="<?php echo $this->htmlEscape($this->getBillingAddress()->getData($helper->getFieldEnable($i))) ?>" title="<?php echo $this->__($fieldValue[$helper->getFieldEnable($i)]) ?>" class="input-text <?php if($helper->getFieldRequire($helper->getFieldEnable($i))||$helper->getFieldEnable($i)=='firstname'||$helper->getFieldEnable($i)=='lastname'||$helper->getFieldEnable($i)=='email') echo 'required-entry'; ?>" />
							<?php if($helper->getFieldEnable($i)=='email'): ?>
								<span id="valid_email_address_image" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/onestepcheckout/valid.gif')?>" title="<?php echo $this->__('Valid Email Address');?>" alt="<?php echo $this->__('Valid Email Address');?>" width="18"/></span>				
								<div id="email-error-message" class="error-message"></div>	
							<?php endif ?>
						<?php endif ?>
					</div>
			<?php if(($i%2!=0)||(($i%2==0)&&(!$helper->getFieldEnable($i+1)||$helper->getFieldEnable($i+1)=='0'||(Mage::getSingleton('customer/session')->isLoggedIn() && $helper->getFieldEnable($i+1)=='email')))): ?>
				</li>
			<?php endif ?>
		<?php endfor ?>
		<?php if($checkCountry==0): ?>
			<div style="display:none;">
				<?php echo $this->getCountryHtmlSelect('billing') ?>
			</div>
		<?php endif ?>
		<?php if (  $this->customerHasAddresses() || !$this->isCustomerLoggedIn() && Mage::helper('onestepcheckout')->enableRegistration() && Mage::helper('onestepcheckout')->allowGuestCheckout()):?>
		<li>
			<div>
				<input id="create_account_checkbox_id" type="checkbox" name="create_account_checkbox" onclick="checkCreatAccount()" value="1" />
				<label for="create_account_checkbox_id"><?php echo $this->__('Create an account for later use') ?></label>
			</div>
		</li>
		
		<?php endif;?>
		<?php if (!$this->isCustomerLoggedIn() && (Mage::helper('onestepcheckout')->enableRegistration() || !Mage::helper('onestepcheckout')->allowGuestCheckout())):?>
		<li id="password_section_id" <?php if (!Mage::helper('onestepcheckout')->allowGuestCheckout()):?>style="display:block"<?php else:?>style="display:none"<?php endif?>>
			<div class="two-fields">
				<label for="billing:customer_password"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br/>
				<input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
			</div>
			<div class="two-fields">
				<label for="billing:confirm_password"><?php echo $this->__('Confirm Password') ?> <span class="required">*</span></label><br/>
				<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
			</div>
		</li>			
		<?php endif?>		
		