<?php 
$max_credit_checkout = $this->getMaxCreditCheckout();
$min_credit_checkout = $this->getMinCreditCheckout();
?>
    <div class="sp-methods">
        <label><?php //echo $this->__('Using Credit') ?></label>
        <div class="discount-form">
            <?php if($this->getCustomerId()):?>
                <?php $credit = Mage::getModel('storecredit/customer')->load($this->getCustomerId())->getData('credit_balance'); ?>
                <p><?php echo $this->__('Maximum credits you can use is: %d', $max_credit_checkout) ?></p>
                <p><?php echo $this->__('Minimum credits required if you use is: %s ', $min_credit_checkout); ?></p>
                <input type="hidden" name="mh_remove_storecredit" id="mh_remove_storecredit" value="0" />
                <div class="input-box">
                    <input class="input-text" placeholder="Enter Credits to use for purchase" id="mh_storecredit_value" name="mh_storecredit_value" style="margin-right: 5px !important; width: 58% !important;" value="<?php if($this->getCreditByCheckout() >0) echo $this->getCreditByCheckout() ?>" />
                    <button type="button" title="<?php echo $this->__('Apply Credit') ?>" class="button" onclick="mhUpdateCredit()" value="<?php echo $this->__('Apply Credits') ?>"><span><span><?php echo $this->__('Apply Credits') ?></span></span></button>
                </div>                
               <?php else:?>
                 <div style="text-align: center; margin-top:10px; border-top: 1px dashed;padding-top: 10px;"><?php echo $this->__("Please <a href='%s'>LOGIN</a> to use credit", Mage::getUrl('customer/account/login',array('mh_storecredit_login' => 1)))?></div>
            <?php endif;?>
        </div>
    </div>

<script type="text/javascript">
//<![CDATA[
	
	function mhUpdateCredit()
	{
		var amount = $('mh_storecredit_value').value;

		if($('mh-osc-column-container')){
			if($('loading-mask')) $('loading-mask').show();
		}else{
			if($('checkout-payment-method-load')) $('checkout-payment-method-load').update($('mh_storecredit_onepage-please-wait').innerHTML);
		}
		
		new Ajax.Request("<?php echo Mage::getUrl('storecredit/checkout_cart/onepagepost',array('_secure'=>Mage::app()->getFrontController()->getRequest()->isSecure()))?>", {
			   method: 'post',
			   postBody: "mh_storecredit_value="+$('mh_storecredit_value').value,
			   onComplete: function(data) {
					$('checkout-payment-method-load').update(data.responseText);
					if($('mh-osc-column-container')){
						updatePaymentMethod(); 
					}
				}
		});
	};
	function updateMhFormCredit()
	{
		if($('mh-osc-column-container')){
			if($('loading-mask')) $('loading-mask').show();
		}else{
			if($('mh-checkout-payment-storecredit'))$('mh-checkout-payment-storecredit').update($('mh_storecredit_onepage-please-wait').innerHTML);
		}
		new Ajax.Request("<?php echo Mage::getUrl('storecredit/checkout_cart/updateformcredit',array('_secure'=>Mage::app()->getFrontController()->getRequest()->isSecure()))?>", {
			   method: 'post',
			   onComplete: function(data) {
					$('mh-checkout-payment-storecredit').update(data.responseText);
					if($('mh-osc-column-container')){
						//updatePaymentMethod();
						if($('loading-mask')) $('loading-mask').hide(); 
					}
				}
		});
	};

//]]>
</script>
<div id="mh_storecredit_onepage-please-wait" style="display: none; ">
	<div class="please-wait">
	    <img src="<?php echo $this->getSkinUrl('mh_storecredit/images/ajax-loader.gif')?>" class="v-middle" alt="loading"> &nbsp; 
	    <?php echo Mage::helper('storecredit')->__("Updating credits ...")?>
	</div>
</div>
