<?php
/**
 * Webmoney Merchant Interface
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Sprinnet_Wmi
 * @copyright  Copyright (c) 2009 SPRINNET Systems, s.r.o. (http://www.sprinnet.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!--fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ;?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
			<div style="display:inline;" ><img  src="<?php echo $this->getSkinUrl('images/webmoney/webmoney_logo.gif') ?>" border="0" alt="Webmoney"></div>
        </li>
        <li>
            <?php echo Mage::helper('webmoney')->__('You will be redirected to WebMoney website when you place an order.') ?>
        </li>
    </ul>
</fieldset-->