
<?php

$_order  = $this->getOrder();
$_source = $this->getSource();

$store_id = Mage::getModel('sales/order')->load($_order->getId())->getStoreId();
$buy_credit = Mage::helper('core')->currency($_order->getMhStorecreditBuyCredit(),false,false);

if ($buy_credit > 0){ ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('storecredit')->__('Earn Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>><?php echo Mage::helper('storecredit')->formatCredit($buy_credit) ?></td>
</tr>
<?php };
?>

