<?php
$invoiceId = (int) $this->getRequest()->getParam('invoice_id');
if ($invoiceId) {
	$invoice = Mage::getModel('sales/order_invoice')->load($invoiceId);
	$order = $invoice->getOrder();
} else {
	$orderId = (int) $this->getRequest()->getParam('order_id');
	$order = Mage::getModel('sales/order')->load($orderId);
}
$currency_code = $order->getOrderCurrencyCode();
$data = $this->getTransactionData($order);
$wmi = Mage::getModel('webmoney/webmoney');
$wmPurses = $wmi->getWmPurses();
$wmPurse = $wmPurses[$currency_code];	
$wmPurse = $wmi->getConfigData( $wmPurse );
?>
<?php echo Mage::helper('webmoney')->__('Webmoney') ?>
{{pdf_row_separator}}
	<?php echo Mage::helper('webmoney')->__('Payer purse: ') ?><?php echo $data['lmi_payer_purse'] ?>
{{pdf_row_separator}}
	<?php echo Mage::helper('webmoney')->__('Payer WM: ') ?><?php echo $data['lmi_payer_wm'] ?>
{{pdf_row_separator}}
	<?php echo Mage::helper('webmoney')->__('Seller purse: ') ?><?php echo $wmPurse ?>