	  
<form action="<?php echo $this->getUrl('storecredit/index/send') ?>" method="post" name="mh_storecredit_send" id="form-validate" >
<div class="dashboard">
	<div class="account-box ad-account-info    box-account box-info">
	    <div class="head    box-head">
	    	<h2 class="sent-credits-friend"><?php echo $this->__('Send Credits To Friend') ?></h2>
	    </div>
	 <div class="fieldset">
	    <ul class="form-list">
	         <li class="fields">
	         	 <div class="field">
	             	<label for="name" class="required"><em>*</em><?php echo $this->__('Friend Name') ?></label>
	             	<div class="input-box">
	             		<input type="text" name="name" id="name" value="" class="input-text required-entry" />      		
	        		</div>
	             </div>
	             
	             <div class="field">
	                <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
	                <div class="input-box">
	                        <input type="text" name="email" id="email" value="" title="<?php echo $this->__('Email') ?>" class="input-text validate-email required-entry" />
	                    </div>
	             </div>
	               
	        </li>
         
            <li class="fields">
                <div class="field">
					<label for="amount" class="required"><em>*</em><?php echo $this->__('Amount') ?></label>
                    <div class="input-box">
                        <input type="text" name="amount" id="amount" value="" title="<?php echo $this->__('Amount') ?>" class="input-text validate-digits validate-greater-than-zero required-entry" />
                    	
                    </div>
			    </div>
			    <div class="field">
					<label for="message"><?php echo $this->__('Message') ?></label>
                    <div class="input-box">
                    	<textarea class="input-text" title="<?php echo $this->__('Message') ?>" name="message" id="message" ></textarea>
                    </div>
			    </div>
            </li>
	     </ul>
	  </div>
	  <div class="buttons-set">   	
      	 <button type="submit" title="<?php echo $this->__('Save') ?>" id="send_amount" class="button"><span><span><?php echo $this->__('Send') ?></span></span></button>
  	  </div>
  </div>
  
</div>
</form>

   
<script type="text/javascript">
	var dataForm = new VarienForm('form-validate', true);
</script>
