<?php
/**
 *
 * @category   MW
 * @package    MW_Credit
 * @author Mage World <support@mage-world.com>
 */
?>
<div id="toggleSection" style="display: none;">
<?php $_credits = $this->getCreditHistory(); ?>
<?php if($_credits->getSize()): ?>
	<?php echo $this->getPagerHtml(); ?>
	<table class="data-table" id="my-storecredits-table">
	    <thead>
	        <tr>
				<th style="text-align: center;"><?php echo $this->__("ID")?></th>
                <th style="text-align: center;"><?php echo $this->__("Date")?></th>
                <th style="text-align: center;"><?php echo $this->__("Amount")?></th>
                <th style="text-align: center;"><?php echo $this->__("Credits")?></th>
                <th style="text-align: center;" ><?php echo $this->__("Message")?></th>
                <th style="text-align: center;"><?php echo $this->__("Status")?></th>
	        </tr>
	    </thead>
	    <tbody>
	        <?php foreach ($_credits as $_credit): ?>
	            <tr style="text-align:left">
	            	<td class="text-align: center;"><?php echo $_credit->getHistoryId(); ?></td>
	                <td style="width: 90px;"><?php echo $this->formatDate($_credit->getTransactionTime())." ".$this->formatTime($_credit->getTransactionTime())?></td>
	            	<td style="text-align: center;"><?php echo $this->getAmount($_credit->getAmount(),$_credit->getTransactionType())?></td>
	            	<td style="text-align: center; font-weight: bold;"><?php echo Mage::helper('core')->currency($_credit->getBalance(),true,false)?></td>
	            	<td><?php echo $this->getTransactionDetail($_credit->getTransactionType(),$_credit->getTransactionParams(),$_credit->getOrderId()); ?></td>
	            	<td style="text-align: center;"><?php echo $this->getStatusText($_credit->getStatus());?></td>
	            </tr>
	        <?php endforeach; ?>
	    </tbody>
	</table>
	<?php echo $this->getPagerHtml(); ?>
	<script type="text/javascript">decorateTable('my-storecredits-table')</script>
<?php endif ?>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery("#active-01").click(function(){
        jQuery("#toggleSection").css("display","block");
        jQuery("#active-01").css("display","none");
        jQuery("#btn-slide-01").css("display","inline");
    
    });
    jQuery("#btn-slide-01").click(function(){
        jQuery("#toggleSection").css("display","none");
        jQuery("#active-01").css("display","inline");
        jQuery("#btn-slide-01").css("display","none");
    
    });
});

</script>