<?php $styleChange = Mage::getStoreConfig('onestepcheckout/style_management/style',Mage::app()->getStore(true)->getId()) ?>
<?php if(!$styleChange || $styleChange=='orange'): ?>
	<?php $styleUse = $this->getSkinUrl('images/onestepcheckout/style/orange/') ?>
<?php else: ?>
	<?php $styleUse = $this->getSkinUrl('images/onestepcheckout/style/'.$styleChange.'/') ?>
<?php endif ?>
<style type="text/css">
	.messages {
	    width: calc(100% - 30px);
	    overflow: hidden;
	    margin-left: 15px !important;
	}
    .step-check-header, #onestepcheckout-button-place-order {
        background: #0fadf3;
        text-transform: uppercase;
        font-size: 15px;
        margin:  0;
        margin-top: 10px;
    }
    .one-step-checkout {
        background: #fff;
        border: 0;
        padding: 20px 0;
    }
	.one-step-checkout h3.step_1
	{
		background:url(<?php echo $styleUse; ?>onestepcheckout_step_1.png) center left no-repeat;
	}

	.one-step-checkout h3.step_2
	{
		background:url(<?php echo $styleUse; ?>onestepcheckout_step_2.png) center left no-repeat;
	}

	.one-step-checkout h3.step_3
	{
		background:url(<?php echo $styleUse; ?>onestepcheckout_step_3.png) center left no-repeat;
	}

	.one-step-checkout h3.step_4
	{
		background:url(<?php echo $styleUse; ?>onestepcheckout_step_4.png) center left no-repeat;
	}

	.one-step-checkout h3.step_5
	{
		background:url(<?php echo $styleUse; ?>onestepcheckout_step_5.png) center left no-repeat;
	}
	#review_step_header{
		background:url(<?php echo $styleUse; ?>review_step_header.png) center left no-repeat !important;
	}
	/*button.btn-checkout span{
		background:url(<?php echo $styleUse; ?>place_button.png) no-repeat scroll 0 0 transparent !important;
		border: 0 none;
		color: #FFFFFF;
		font: bold 15px/40px Arial,Helvetica,sans-serif;
		height: 40px;
		padding: 0 0 0 9px;
	}
	button.btn-checkout span span {
		background-position: 100% 0 !important;
		padding: 0 25px 0 16px;
	}*/
	button#add_coupon_code_button span{
		background:url(<?php echo $styleUse; ?>apply_coupon.png) repeat scroll 0 0 transparent !important;
		border: 0 none;
		color: #FFFFFF;
		/*height: 40px;
		padding: 0 0 0 9px;*/
	}
	button#remove_coupon_code_button span{
		background:url(<?php echo $styleUse; ?>apply_coupon.png) repeat scroll 0 0 transparent !important;
		border: 0 none;
		color: #FFFFFF;
		/*height: 40px;
		padding: 0 0 0 9px;*/
	}
	button#add_coupon_code_button span span {
		background-position: 100% 0 !important;
		/*padding: 0 25px 0 16px;*/
	}
	.ajax-loader1{
		background:url(<?php echo $styleUse; ?>loading-icon.gif) top left no-repeat !important;
	}
	.ajax-loader2{
		background:url(<?php echo $styleUse; ?>loading-icon.gif) top left no-repeat !important;
	}
	.ajax-loader3{
		background:url(<?php echo $styleUse; ?>loading-icon.gif) top left no-repeat !important;
	}
	button.place-order-loader span {
		background:none repeat scroll 0 0 #CCCCCC !important;
		border: 0 none;
		color: #FFFFFF;
		font: bold 15px/40px Arial,Helvetica,sans-serif;
		height: 40px;
		padding: 0 0 0 9px;
	}
</style>

<div id="ajaxcart-load-ajax" style="display:none;">
	<div id="load" class="ajaxcart-overlay">&nbsp;</div>
	<div id="ajaxcart-loading" class="ajaxcart-loading">
		<img alt="<?php echo $this->__('Loading') ?>..." src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" /><br />
		<?php echo $this->__('Loading') ?>...
	</div>
	<div id="form-paypal" style="display:none;" class="form-paypal">
	</div>
</div>
<ol class="one-step-checkout clearfix">
	<li class="need-padding">
		<h1 class="checkout_header"><?php echo $this->getCheckoutTitle();?></h1>
		<p style="font-size:18px;" class="pleaset"><?php echo $this->configData['checkout_description'] ? $this->configData['checkout_description'] : 'Please fill in the fields below and click Place order to complete your purchase!';?></p>
	</li>
	<?php if ($this->isShowLoginLink() && !$this->isCustomerLoggedIn()):?>
	<li class="onestepcheckout-login-link need-padding">
		<!--<a href="#" id="show-login" onclick ="showloginbox();return false;">-->
		<a href="javascript:void(0);"  id="onestepcheckout-login-link">
		<?php echo $this->__('Already have an account?Click here to login')?>
		</a>
	</li>
	<?php endif?>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<li class="address-order">
		<form id="one-step-checkout-form" method="post" action="<?php echo $this->getCheckoutUrl(); ?>">
			
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4  address-information_ <?php if ($this->configData['page_layout'] == '3columns'):?>address-info-3-columns_<?php endif;?>">
				<div class="itemrow">
					<?php echo $this->getChildHtml('onestepcheckout.billing');?>				
				</div>

			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 order-information_ <?php if ($this->configData['page_layout'] == '3columns'):?>order-info-3-columns_<?php endif;?>">
				<div class="itemrow">
					<ol>
						<li class="payment-method">						
							<h3 class="step-check-header">
								<?php echo $this->__('step 2: Payment Method'); ?>
							</h3>						
							<?php echo $this->getChildHtml('onestepcheckout.payment_method'); ?>												
						</li>
						<?php if ($this->configData['page_layout'] == '2columns'):?>
						<li class="order-review-info">	
									
							<h3 class="step-check-header">
								<?php echo $this->__('step 3: Order Review'); ?>
							</h3>		
							<div class="clss-rv">				
								<?php echo $this->getChildHtml('onestepcheckout.review') ?>						
								<div class="ajax-loader3" id="ajax-loader3"  style="display:none;"></div>
							</div>
						</li>
						<?php endif;?>
					</ol>
				</div>
			</div>
			<?php if ($this->configData['page_layout'] == '3columns'):?>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4  order-review-section_">
				<div class="itemrow">
					<ol>
						<li class="order-review-info">	
												
							<h3 <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()):?> class="step_4" <?php else:?> class="step-check-header"<?php endif?>>
								<?php echo $this->__('step 3: Order Review'); ?>
							</h3>		
							<div class="clss-rv">				
								<?php echo $this->getChildHtml('onestepcheckout.review') ?>						
								<div class="ajax-loader3" id="ajax-loader3"  style="display:none;"></div>
							</div>
						</li>
					</ol>
				</div>
			</div>
			<?php endif;?>
			<?php $_helper = Mage::helper('onestepcheckout');?>
			<?php if(!$_helper->isCustomerLoggedIn() && $_helper->showLoginLink()): ?>
				<?php echo $this->getChildHtml('login-popup'); ?>
			<?php endif; ?>			
		</form>
	</li>
</ol>

<script type="text/javascript">
//<![CDATA[	
	var preloadImage = '<?php echo $this->getSkinUrl('images/onestepcheckout/preload.gif')?>';
	var shipping_method_url = '<?php echo $this->getUrl('onestepcheckout/index/save_shipping', array('_secure' => true));?>';
	var enable_update_payment = <?php echo $this->configData['update_payment'] ? 'true' : 'false'; ?>;
    var login_url = '<?php echo $this->getUrl('onestepcheckout/index/show_login', array('_secure' => true));?>';	
	var show_login_link = <?php echo $this->configData['show_login_link'] ? 'true' : 'false'; ?>;
	var show_term_condition_url = '<?php echo $this->getUrl('onestepcheckout/index/show_term_condition', array('_secure' => true));?>';
	var form = $('one-step-checkout-form');
	var reload_payment = <?php echo $this->configData['reload_payment']; ?>
	
	function showloginbox() {
		var url = '<?php echo $this->getUrl('onestepcheckout/index/show_login', array('_secure' => true));?>';
		showLogin(url);
	}

	function showforgotpwd() {
		var url = '<?php echo $this->getUrl('onestepcheckout/index/show_password', array('_secure' => true));?>';
		showpwdbox(url);
	}
	
	function showPasswordForm() {
		$('onestepcheckout-login').hide();
		$('onestepcheckout-forgot-password').show();
	}
	
	function showloginform() {
		$('onestepcheckout-forgot-password').hide();
		$('onestepcheckout-login').show();		
	}
	
	function submitLoginForm() {
		var login_validator = new Validation('onestepcheckout-login-form');
		if (login_validator.validate()) {
			showLoginLoading();
			var url = '<?php echo $this->getUrl('onestepcheckout/index/loginPost', array('_secure' => true))?>';
			var email = $('osclogin:email_address').value;
			var password = $('osclogin:password').value;
			var parameters = {email:email, password:password};			
			var loginRequest = new Ajax.Request(url, {
				parameters: parameters,
				onComplete: loginProcess.bindAsEventListener(this),
				onFailure: ""
			});						
		}
	}
	
	function retrievePassword() {
		var passwordValidator = new Validation('osc-forgotpassword-form');
		if (passwordValidator.validate()) {
			showPassLoading();
			var url = '<?php echo $this->getUrl('onestepcheckout/index/retrievePassword', array('_secure' => true))?>';
			var email = $('forgotpassword_email_address').value;
			var parameters = {email:email};			
			var loginRequest = new Ajax.Request(url, {
				parameters: parameters,
				onComplete: passwordProcess.bindAsEventListener(this),
				onFailure: ""
			});
		}
	}
		
	
	<?php if ($this->configData['enable_ajax']):?>
		var save_address_url = '<?php echo $this->getUrl('onestepcheckout/index/save_address', array('_secure' => true))?>';
		
		<?php if ($this->isAjaxBillingField('country')):?>
			//save billing when country is changed
			Event.observe('billing:country_id', 'change', function() {
				//check empty fields
				var empty = checkEmptyFields($('billing-new-address-form'));
				if(empty == false || reload_payment==2)
					save_address_information(save_address_url);
			});
			<?php if ($this->isShowShippingAddress()):?>
			Event.observe('shipping:country_id', 'change', function() {
				//check empty fields
				var empty = checkEmptyFields($('shipping-new-address-form'));
				if(empty == false || reload_payment==2)
					save_address_information(save_address_url);
			});
			<?php endif;?>
		<?php endif;?>
		
		<?php if ($this->isAjaxBillingField('state/region')):?>
			//save billing when state / region is changed
				Event.observe('billing:region_id', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				Event.observe('billing:region', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php if ($this->isShowShippingAddress()):?>
				Event.observe('shipping:region_id', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				Event.observe('shipping:region', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php endif;?>
		<?php endif;?>
		
		<?php if ($this->isAjaxBillingField('postcode')):?>
			//save billing when postcode is changed
				Event.observe('billing:postcode', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php if ($this->isShowShippingAddress()):?>
				Event.observe('shipping:postcode', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php endif;?>
		<?php endif;?>
		
		<?php if ($this->isAjaxBillingField('city')):?>
			//save billing when city is changed
				Event.observe('billing:city', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('billing-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});
				<?php if ($this->isShowShippingAddress()):?>
				Event.observe('shipping:city', 'change', function() {
					//check empty fields
					var empty = checkEmptyFields($('shipping-new-address-form'));
					if(empty == false || reload_payment==2)
						save_address_information(save_address_url);
				});			
				<?php endif;?>
		<?php endif;?>
		
		//telephone
		Event.observe('billing:telephone', 'change', function() {
			//check empty fields
			var empty = checkEmptyFields($('billing-new-address-form'));
			if(empty == false)
				save_address_information(save_address_url);
		});
		Event.observe('shipping:telephone', 'change', function() {
			//check empty fields
			var empty = checkEmptyFields($('shipping-new-address-form'));
			if(empty == false)
				save_address_information(save_address_url);
		});
	<?php endif?>			
	
	//document.observe('dom:loaded', function() {
	//fix for IE9
	Event.observe(window, 'load', function() {
		if($RF(form, 'payment[method]') != null)	{		
			var payment_method = $RF(form, 'payment[method]');
			if ($('container_payment_method_' + payment_method)) {
				$('container_payment_method_' + payment_method).show();
			}
			if ($('payment_form_' + payment_method)) {
				$('payment_form_' + payment_method).show();		
			}
		}
	});
	
	function disable_payment(){
		var options = document.getElementsByName('payment[method]');
		for(var i=0;i<options.length;i++){
			if(!$(options[i].id).checked){
				var container = options[i].id.replace('p_method','container_payment_method');
				if($(container)){
					$(container).innerHTML = '';
				}
			}
		}	
	}

	function checkpayment(){
	var options = document.getElementsByName('payment[method]');
		var pay = true;
		for(var i=0;i<options.length;i++){
			if($(options[i].id).checked){
				pay = false;
				break;
			}
		}
		if(pay==true){
			return false;
		}
		return true;
	}
	/*
	Event.observe(window, 'load', function() {
		$$('#onestepcheckout-button-place-order').each(function(elem){
			elem.observe('click', function(e)   {
				Event.stop(e);
				// First validate the form
				var form = new VarienForm('one-step-checkout-form');
				if(!form.validator.validate())  {
					Event.stop(e);
				}else{
					if($('p_method_hosted_pro') && $('p_method_hosted_pro').checked){
						$('onestepcheckout-place-order-loading').show();
						$('onestepcheckout-button-place-order').removeClassName('btn-checkout');
						$('onestepcheckout-button-place-order').addClassName('place-order-loader');
						$('ajaxcart-load-ajax').show();
						checkAjax('<?php echo $this->getUrl('onestepcheckout/index/saveOrderPro', array('_secure' => true));; ?>');
					}else{
						already_placing_order = true;
						$('onestepcheckout-button-place-order').disabled = true;
						disable_payment();
						$('onestepcheckout-place-order-loading').show();
						$('onestepcheckout-button-place-order').removeClassName('btn-checkout');
						$('onestepcheckout-button-place-order').addClassName('place-order-loader');
						$('one-step-checkout-form').submit();
					}
				}
			});
		});	
	});
	*/
	function oscPlaceOrder(element){
		var clForm = new VarienForm('one-step-checkout-form', true);
        if (clForm.validator.validate() == false) {
            return false;
        }
		clForm.submit();
	}
	
	function checkAjax(url){	
		var form = $('one-step-checkout-form');		
		var payment_method = $RF(form, 'payment[method]');
		var shipping_method = $RF(form, 'shipping_method');		
		var parameters = {
            payment : payment_method,
			shipping_method : shipping_method			
		}
		get_billing_data(parameters);	
		get_shipping_data(parameters);
		
		if($('giftmessage-type') && $('giftmessage-type').value != ''){
			parameters[$('giftmessage-type').name] = $('giftmessage-type').value;
		}
		if($('create_account_checkbox_id') && $('create_account_checkbox_id').checked){
			parameters['create_account_checkbox'] = 1;
		}	
		if($('gift-message-whole-from') && $('gift-message-whole-from').value != ''){
			parameters[$('gift-message-whole-from').name] = $('gift-message-whole-from').value;
		}
		if($('gift-message-whole-to') && $('gift-message-whole-to').value != ''){
			parameters[$('gift-message-whole-to').name] = $('gift-message-whole-to').value;
		}
		if($('gift-message-whole-message') && $('gift-message-whole-message').value != ''){
			parameters[$('gift-message-whole-message').name] = $('gift-message-whole-message').value;
		}
		if($('billing-address-select') && $('billing-address-select').value != ''){
			parameters[$('billing-address-select').name] = $('billing-address-select').value;
		}
		if($('shipping-address-select') && $('shipping-address-select').value != ''){
			parameters[$('shipping-address-select').name] = $('shipping-address-select').value;
		}

		new Ajax.Request(url,{
			method: 'post',
			evalJS: 'force',
			onSuccess: function(transport){
				// alert(JSON.parse(transport.responseText).url);
				if(JSON.parse(transport.responseText).url=='null' || JSON.parse(transport.responseText).url==null){
					$('ajaxcart-loading').style.display='block';
					$('ajaxcart-loading').style.top='15%';
					$('ajaxcart-loading').style.left='40%';
					$('ajaxcart-loading').style.width='551px';
					$('ajaxcart-loading').style.height='400px';
					$('ajaxcart-loading').style.overflow='hidden';
					$('ajaxcart-loading').style.padding='5px';		
					$('ajaxcart-loading').innerHTML=JSON.parse(transport.responseText).html;
					$('iframe-warning').style.textAlign='left';					
				}
				else
				{					
					window.location.href= JSON.parse(transport.responseText).url;
				}
			},
			onFailure: function(transport){  
			},
			parameters: parameters
		});
	}	
	
	<?php //if ($this->isCustomerLoggedIn()):?>
	var save_address_url = '<?php echo $this->getUrl('onestepcheckout/index/save_address', array('_secure' => true))?>';
	save_address_information(save_address_url);
	<?php //endif;?>
	
//]]>
</script>

<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>
<div id="loading-process" style="display: none;"></div>

<!-- Terms and conditions -->
<?php $_helper = Mage::helper('onestepcheckout');?>
<?php $width = $_helper->getTermPopupWidth() ? $_helper->getTermPopupWidth() : 482;?>
<?php $height = $_helper->getTermPopupHeight() ? $_helper->getTermPopupHeight() : 530;?>
<?php if($_helper->enableTermsAndConditions()): ?>
	<?php if(!$_helper->enableCustomSize()): ?>
	<div id="onestepcheckout-toc-popup" style="display:none;">
		<div class="onestepcheckout-popup-wrapper" style="height: 515px !important;">
			<div class="onestepcheckout-popup-wrapper-inner">
				<h1><?php echo $_helper->getTermTitle(); ?></h1>

				<div class="onestepcheckout-toc-terms">
					<?php echo $_helper->getTermsConditionsHtml(); ?>
				</div>

				<p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
			</div>
		</div>
		<div class="onestepcheckout-popup-footer">&nbsp;</div>
	</div>
	<?php else:?>
		<div id="onestepcheckout-toc-popup" style="display:none; width:<?php echo $width?>px; height:<?php echo $height?>px;">
		<div class="onestepcheckout-popup-wrapper2" style="width:<?php echo $width?>px; height:<?php echo $height?>px;">
			<div class="onestepcheckout-popup-wrapper-inner2">
				<h1><?php echo $_helper->getTermTitle(); ?></h1>

				<div class="onestepcheckout-toc-terms">
					<?php echo $_helper->getTermsConditionsHtml(); ?>
				</div>

				<p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
			</div>
		</div>
		<div class="onestepcheckout-popup-footer2">&nbsp;</div>
	</div>
	<?php endif; ?>
<script>
Event.observe(window, 'load', function() {

    var termsPopup = new Control.Modal($('onestepcheckout-toc-popup'), {
        overlayOpacity: 0.65,
        fade: true,
        fadeDuration: 0.3
    });

    $('onestepcheckout-toc-link').observe('click', function(e) {
        e.preventDefault();
        termsPopup.open();
    });

    $$('div#onestepcheckout-toc-popup p.close a').invoke('observe', 'click', function(e) {
        e.preventDefault();
        termsPopup.close();
    });

});

/*
var popup;
Event.observe(window, 'load', function() {
    popup = new OneStepCheckout_Popup('onestepcheckout-toc-popup','onestepcheckout-toc-link', 'div#onestepcheckout-toc-popup p.close a');
});
*/
</script>
<?php endif; ?>
